name: Push File

on: push

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: curl
      run: curl https://raw.githubusercontent.com/schemaorg/schemaorg/main/data/releases/14.0/schemaorg-current-http.ttl > schemaorg-current-http.ttl
    - name: display file
      run: echo "$(<schemaorg-current-http.ttl)"
    - name: Run remake database
      run: ./controllers/ApplicationsController.js
