name: Push File

on: push

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      run: curl https://raw.githubusercontent.com/schemaorg/schemaorg/main/data/releases/14.0/schemaorg-current-http.ttl > schemaorg-current-http.ttl
    - name: display file
      run: echo "$(<schemaorg-current-http.ttl)"
    - name: Commit file
      run: |
        git config --global user.email "krzysiek.p97@gmail.com"
        git config --global user.name "PiotrowskiKrzysztof"
        git add schemaorg-current-http.ttl
        git commit -m "new vocabulary version"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: main
        github_token: ${{ secrets.API_TOKEN_GITHUB }}
        force: true
      
