name: Push File

on: push

env:
  MONGODB_URI: ${{ secrets.MONGODB_URI }}

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: current version schema
      run: curl https://raw.githubusercontent.com/schemaorg/schemaorg/main/versions.json > version.json
    - name: curl
      run: |
        $file = file_get_contents($url);
        $array = json_decode($file, true);
    - name: display ttl
      run: echo "$(<schemaorg-current-http.ttl)"
