name: Push File

on: push

env:
  MONGODB_URI: ${{ secrets.MONGODB_URI }}

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: current version schema
      run: curl https://raw.githubusercontent.com/schemaorg/schemaorg/main/versions.json > version.json
    - name: display file
      run: echo "$(<version.json)"
    - name: curl
      run: curl https://raw.githubusercontent.com/schemaorg/schemaorg/main/data/releases/14.0/schemaorg-current-http.ttl > schemaorg-current-http.ttl
    - name: display file
      run: echo "$(<schemaorg-current-http.ttl)"
