name: Push File

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: CopyCat
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.API_TOKEN_GITHUB }}
        src_path: /schemaorg/data/releases/14.0/schemaorg-current-http.ttl
        dst_path: /
        dst_owner: PiotrowskiKrzysztof
        dst_repo_name: generatorschema
