name: Push File

on: push

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: https://raw.githubusercontent.com/PiotrowskiKrzysztof/schemaorg/main/data/releases/14.0/schemaorg-current-http.ttl
          
      
