name: Push File

on: push

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      run: curl https://raw.githubusercontent.com/schemaorg/schemaorg/main/data/releases/14.0/schemaorg-current-http.ttl > schemaorg-current-http.ttl
    - name: display file
      run: echo "$(<schemaorg-current-http.ttl)"
    - name: move file to dir
      run: |
        mkdir -p ./output/
        yes| cp -rf schemaorg-current-http.ttl ./output/
    - uses: actions/checkout@v3
    - run: |
        git config user.email "krzysiek.p97@gmail.com"
        git config user.name "PiotrowskiKrzysztof"
        git add ./output
        git commit -m "new vocabulary version"
        git push
